
services:
  zebrands-server:
    build:
      context: ./catalog-system
      dockerfile: DockerFileProd
    ports:
      - "3001:8000"
    env_file:
      - ./catalog-system/.env
    command: bash -c "uv run manage.py makemigrations && uv run manage.py migrate && uv run manage.py runserver_ 0.0.0.0:8000"